before_script:
  - echo "Before script"
  - cd /var/www/html/{your-project-name} #your project path
building:
  stage: build
  script:
    - git checkout main
    - git pull origin main
    - composer install
    - php artisan migrate
    - php artisan cache:clear
    - php artisan config:clear
    - sudo chown -R deployer:www-data /var/www/html/tavsir-api/
    - find /var/www/html/tavsir-api -type f -exec chmod 664 {} \;
    - find /var/www/html/tavsir-api -type d -exec chmod 775 {} \;
    - chgrp -R www-data storage bootstrap/cache
    - chmod -R ug+rwx storage bootstrap/cache

deploying:
  stage: deploy
  environment:
    name: production
  script:
    - echo "Deployed"
  only:
    - main